### ISSUE TITLE
Code | Pyramid Pattern 1

### ISSUE THREAD

**Issue by aryashah2k** [PatternHouse/CPlusPlus-PatternHouse#65]

**Comment by kashyap1905** [comment]
@aryashah2k  Can you please assign all the issues for the pyramid pattern (from 1 to 93) to me !!

**Comment by aryashah2k** [comment]
I will be able ot assign you more once all the remaining issues are resolved. You can tag me again when all are done and I will assign these issues. Since you already have 1-93 of C-PatternHouse, I will keep this open for other participants to contribute too. 
Hope you understand, good luck!

**Comment by kashyap1905** [comment]
> I will be able ot assign you more once all the remaining issues are resolved. You can tag me again when all are done and I will assign these issues. Since you already have 1-93 of C-PatternHouse, I will keep this open for other participants to contribute too. Hope you understand, good luck!

Okay Okay. But can you please assign me from 1 to 20 only! since I have solved from 1 to 20 and pushed the code to my local repository. I thought you will assign me and so started working. So if you please assign me issues from 1 to 20 only, it would be great for me.

@aryashah2k
